mod commands;
pub mod core;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    #[cfg(debug_assertions)]
    {
        tauri::Builder::default()
            .manage(commands::audio::RecordingManager::default())
            .plugin(tauri_plugin_dialog::init())
            .plugin(tauri_plugin_shell::init())
            .invoke_handler(tauri::generate_handler![
                commands::audio::audio_reveal_wav,
                commands::audio::audio_save_wav,
                commands::audio::recording_start,
                commands::audio::recording_status,
                commands::audio::recording_stop,
                commands::coach::mascot_get_context_message,
                commands::coach::progress_get_snapshot,
                commands::coach::talks_get_blueprint,
                commands::feedback::analyze_attempt,
                commands::feedback::feedback_context_get,
                commands::feedback::feedback_get,
                commands::feedback::feedback_note_get,
                commands::feedback::feedback_note_set,
                commands::feedback::feedback_timeline_list,
                commands::outline::export_outline,
                commands::outline::outline_get,
                commands::outline::outline_set,
                commands::pack::pack_inspect,
                commands::pack::pack_export,
                commands::pack::peer_review_import,
                commands::peer_review::peer_review_get,
                commands::peer_review::peer_review_list,
                commands::preferences::preference_global_get,
                commands::preferences::preference_global_set,
                commands::preferences::preference_profile_get,
                commands::preferences::preference_profile_set,
                commands::profile::profile_create,
                commands::profile::profile_delete,
                commands::profile::profile_db_diagnostics,
                commands::profile::profile_list,
                commands::profile::profile_rename,
                commands::profile::profile_switch,
                commands::project::project_create,
                commands::project::project_ensure_training,
                commands::project::project_get_active,
                commands::project::project_list,
                commands::project::project_set_active,
                commands::project::project_update,
                commands::quest::quest_get_daily,
                commands::quest::quest_get_by_code,
                commands::quest::quest_list,
                commands::quest::quest_attempts_list,
                commands::quest::quest_report,
                commands::quest::quest_submit_audio,
                commands::quest::quest_submit_text,
                commands::run::run_analyze,
                commands::run::run_create,
                commands::run::run_finish,
                commands::run::run_get,
                commands::run::run_get_latest,
                commands::run::run_list,
                commands::run::run_set_transcript,
                commands::transcription::transcribe_audio,
                commands::transcription::transcript_get,
                commands::transcription::transcript_export,
                commands::transcription::asr_models_list,
                commands::transcription::asr_model_download,
                commands::transcription::asr_model_remove,
                commands::transcription::asr_model_verify,
                commands::transcription::asr_sidecar_status,
                commands::security::security_prepare_appdata_file,
                commands::security::security_probe_fs
            ])
            .run(tauri::generate_context!())
            .expect("error while running tauri application");
    }

    #[cfg(not(debug_assertions))]
    {
        tauri::Builder::default()
            .manage(commands::audio::RecordingManager::default())
            .plugin(tauri_plugin_dialog::init())
            .plugin(tauri_plugin_shell::init())
            .invoke_handler(tauri::generate_handler![
                commands::audio::audio_reveal_wav,
                commands::audio::audio_save_wav,
                commands::audio::recording_start,
                commands::audio::recording_status,
                commands::audio::recording_stop,
                commands::coach::mascot_get_context_message,
                commands::coach::progress_get_snapshot,
                commands::coach::talks_get_blueprint,
                commands::feedback::analyze_attempt,
                commands::feedback::feedback_context_get,
                commands::feedback::feedback_get,
                commands::feedback::feedback_note_get,
                commands::feedback::feedback_note_set,
                commands::feedback::feedback_timeline_list,
                commands::outline::export_outline,
                commands::outline::outline_get,
                commands::outline::outline_set,
                commands::pack::pack_inspect,
                commands::pack::pack_export,
                commands::pack::peer_review_import,
                commands::peer_review::peer_review_get,
                commands::peer_review::peer_review_list,
                commands::preferences::preference_global_get,
                commands::preferences::preference_global_set,
                commands::preferences::preference_profile_get,
                commands::preferences::preference_profile_set,
                commands::profile::profile_create,
                commands::profile::profile_delete,
                commands::profile::profile_db_diagnostics,
                commands::profile::profile_list,
                commands::profile::profile_rename,
                commands::profile::profile_switch,
                commands::project::project_create,
                commands::project::project_ensure_training,
                commands::project::project_get_active,
                commands::project::project_list,
                commands::project::project_set_active,
                commands::project::project_update,
                commands::quest::quest_get_daily,
                commands::quest::quest_get_by_code,
                commands::quest::quest_list,
                commands::quest::quest_attempts_list,
                commands::quest::quest_report,
                commands::quest::quest_submit_audio,
                commands::quest::quest_submit_text,
                commands::run::run_analyze,
                commands::run::run_create,
                commands::run::run_finish,
                commands::run::run_get,
                commands::run::run_get_latest,
                commands::run::run_list,
                commands::run::run_set_transcript,
                commands::transcription::transcribe_audio,
                commands::transcription::transcript_get,
                commands::transcription::transcript_export,
                commands::transcription::asr_models_list,
                commands::transcription::asr_model_download,
                commands::transcription::asr_model_remove,
                commands::transcription::asr_model_verify,
                commands::transcription::asr_sidecar_status
            ])
            .run(tauri::generate_context!())
            .expect("error while running tauri application");
    }
}
