/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBadge: typeof import('./src/components/ui/AppBadge.vue')['default']
    AppButton: typeof import('./src/components/ui/AppButton.vue')['default']
    AppDialog: typeof import('./src/components/ui/AppDialog.vue')['default']
    AppHeaderMenu: typeof import('./src/components/AppHeaderMenu.vue')['default']
    AppPanel: typeof import('./src/components/ui/AppPanel.vue')['default']
    AudioRecorder: typeof import('./src/components/AudioRecorder.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    EntityRow: typeof import('./src/components/EntityRow.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PageShell: typeof import('./src/components/PageShell.vue')['default']
    RecorderAdvancedDrawer: typeof import('./src/components/recorder/RecorderAdvancedDrawer.vue')['default']
    RecorderCapturePanel: typeof import('./src/components/recorder/RecorderCapturePanel.vue')['default']
    RecorderExportPanel: typeof import('./src/components/recorder/RecorderExportPanel.vue')['default']
    RecorderQuickCleanPanel: typeof import('./src/components/recorder/RecorderQuickCleanPanel.vue')['default']
    RecorderWaveform: typeof import('./src/components/recorder/RecorderWaveform.vue')['default']
    RouteContextBar: typeof import('./src/components/shell/RouteContextBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionPanel: typeof import('./src/components/SectionPanel.vue')['default']
    SecurityProbe: typeof import('./src/components/SecurityProbe.vue')['default']
    SidebarIconNav: typeof import('./src/components/shell/SidebarIconNav.vue')['default']
    TalkStepPageShell: typeof import('./src/components/TalkStepPageShell.vue')['default']
    TalkStepTabs: typeof import('./src/components/TalkStepTabs.vue')['default']
    TopPrimaryNav: typeof import('./src/components/shell/TopPrimaryNav.vue')['default']
    UBadge: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+exte_de8bba3212ab9ac0762d9b96edb9e4e2/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UBreadcrumb: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+exte_de8bba3212ab9ac0762d9b96edb9e4e2/node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue')['default']
    UButton: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+exte_de8bba3212ab9ac0762d9b96edb9e4e2/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+exte_de8bba3212ab9ac0762d9b96edb9e4e2/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UInput: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+exte_de8bba3212ab9ac0762d9b96edb9e4e2/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+exte_de8bba3212ab9ac0762d9b96edb9e4e2/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USelect: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+exte_de8bba3212ab9ac0762d9b96edb9e4e2/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USwitch: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+exte_de8bba3212ab9ac0762d9b96edb9e4e2/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTextarea: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.4.0_@tiptap+exte_de8bba3212ab9ac0762d9b96edb9e4e2/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    WindowChrome: typeof import('./src/components/shell/WindowChrome.vue')['default']
    WorkspaceSwitcher: typeof import('./src/components/WorkspaceSwitcher.vue')['default']
  }
}
